<a href="https://colab.research.google.com/github/meow-codes201/learn-deep-learning-in-pytorch/blob/main/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
x = torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
shaped = x.reshape(2,5)
shaped,shaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
shaped = x.reshape(10,1)
shaped,shaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
shaped = x.reshape(5,2)
shaped,shaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
shaped = x.view(2,5)
shaped,shaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
shaped[:,0]=5
shaped,x

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x,x,x,x,x,x,x],dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])

In [ ]:
x = x.reshape(10,1)
z = x.squeeze()
x,x.shape,z,z.shape

(tensor([[ 5.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 5.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]),
 torch.Size([10]))

In [ ]:
w = z.unsqueeze(dim=1)
w,w.shape

(tensor([[ 5.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 5.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 200, 8))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(0,2,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 200, 8])
New shape: torch.Size([224, 8, 200])


In [22]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [23]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
x[0][0]

tensor([1, 2, 3])

In [27]:
x[0,0,0]

tensor(1)

In [26]:
x[:,0]

tensor([[1, 2, 3]])

In [28]:
x[:,2]

tensor([[7, 8, 9]])

In [34]:
x[0,0
  ,1]

tensor(2)

In [35]:
x[0,2,2]

tensor(9)

In [38]:
import torch
import numpy as np
ar = np.arange(1.0,10.0)
ten = torch.from_numpy(ar).type(torch.float32)
new_ar = ten.numpy()
ar,ten,new_ar

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32))

In [39]:
ar += 1
ar,ten,new_ar

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32))

In [44]:
tn = torch.ones(10)
a = tn.numpy()
tn,a

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [48]:
tn = tn + 1
tn,a

(tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

In [2]:
import torch
torch.rand(3,3)

tensor([[0.7341, 0.5686, 0.7414],
        [0.0425, 0.8588, 0.5791],
        [0.8133, 0.9978, 0.3661]])

In [9]:
import torch
import random

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
ranA = torch.rand(3,4)
torch.manual_seed(seed=RANDOM_SEED)
ranB = torch.rand(3,4)
print(ranA)
print(ranB)
print(ranA == ranB)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [10]:
!nvidia-smi

Fri Dec 26 07:52:46 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import torch
torch.cuda.is_available()

True

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
torch.cuda.device_count()

1

In [7]:

import torch
tr = torch.tensor([1,2,3,4])
print(tr,tr.device)

tr_gpu = tr.to(device)
print(tr_gpu,tr_gpu.device)

tensor([1, 2, 3, 4]) cpu
tensor([1, 2, 3, 4], device='cuda:0') cuda:0


In [9]:
tr_gpu = tr_gpu.cpu().numpy()
print(tr_gpu,tr_gpu.device)

[1 2 3 4] cpu
